---
- name: Join control node to Kubernetes control plane.
  command: "{{ kubernetes_join_command }} --control-plane --apiserver-advertise-address {{ kubernetes_apiserver_advertise_address }} --apiserver-bind-port 6443 --certificate-key {{ kubernetes_certificate }} --ignore-preflight-errors='all'"
  register: join_ctrl_plane
  args:
    creates: /etc/kubernetes/kubelet.conf
  tags: ["skip_ansible_lint"]
