---
- name: Create the directory for the kubernetes_config_file
  file:
    path: "{{ kubernetes_kubeadm_kubelet_config_file_path | dirname }}"
    state: directory

- name: Deploy the config-file for kubeadm and kubelet
  template:
    src: "kubeadm-kubelet-config.j2"
    dest: "{{ kubernetes_kubeadm_kubelet_config_file_path }}"


- name: Initialize Kubernetes control plane with kubeadm init without kube-proxy
  command: >
    kubeadm init
    --config {{ kubernetes_kubeadm_kubelet_config_file_path }}
    --skip-phases=addon/kube-proxy
    {{ kubernetes_kubeadm_init_extra_opts }}
  register: kubeadmin_init
  when:
    - not kubernetes_init_stat.stat.exists
    - kubernetes_ignore_preflight_errors is not defined

- name: Initialize Kubernetes control plane with kubeadm init without kube-proxy and ignore_preflight_errors
  command: >
    kubeadm init
    --config {{ kubernetes_kubeadm_kubelet_config_file_path }}
    --ignore-preflight-errors={{ kubernetes_ignore_preflight_errors }}
    --skip-phases=addon/kube-proxy
    {{ kubernetes_kubeadm_init_extra_opts }}
  register: kubeadmin_init
  when:
    - not kubernetes_init_stat.stat.exists
    - kubernetes_ignore_preflight_errors is defined

- name: Print the init output to screen.
  debug:
    var: kubeadmin_init.stdout
    verbosity: 2
  when: not kubernetes_init_stat.stat.exists

- name: Ensure .kube directory exists.
  file:
    path: ~/.kube
    state: directory
    mode: 0755

- name: Symlink the kubectl admin.conf to ~/.kube/conf.
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link
    mode: 0644

- name: Allow pods on control plane (if configured).
  command: "kubectl taint nodes {{ inventory_hostname }} node-role.kubernetes.io/control-plane-"
  register: taint_removed
  until: >
    ("untainted" in taint_removed.stdout) or
    ("not found" in taint_removed.stderr)
  changed_when: "'untainted' in taint_removed.stdout"
  failed_when: false
  retries: 100
  delay: 5
  when:
    - kubernetes_allow_pods_on_control_plane | bool

- name: Write Cilium Helm values to file
  copy:
    dest: "/tmp/cilium_helm.yaml"
    content: "{{ kubernetes_cilium_values | to_yaml }}"
  when:
    - kubernetes_pod_network.cni == 'cilium'
    - not kubernetes_init_stat.stat.exists

- name: Taint nodes with cilium agent-not-ready
  command: kubectl taint nodes --all node.cilium.io/agent-not-ready=true:NoExecute
  when:
    - kubernetes_pod_network.cni == 'cilium'
    - not kubernetes_init_stat.stat.exists
  register: cilium_taint
  changed_when: "'tainted' in cilium_taint.stdout"
  until: cilium_taint is not failed
  retries: 12
  delay: 5

- name: Install Prerequisite CRDs for Cilium Gateway API support.
  register: gateway_crds
  changed_when: "'created' in gateway_crds.stdout"
  command: "kubectl apply -f {{ item }}"
  loop:
    - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_httproutes.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml
    - https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml


- name: Configure Cilium networking
  command: >
    /usr/local/bin/cilium install
    --version {{ kubernetes_cilium_version }}
    --datapath-mode {{ kubernetes_cilium_datapath }}
    --values /tmp/cilium_helm.yaml
  when:
    - kubernetes_pod_network.cni == 'cilium'
    - not kubernetes_init_stat.stat.exists
  register: cilium_result
  changed_when: "'Error' not in cilium_result.stdout"
  until: cilium_result is not failed
  retries: 20
  delay: 5

